name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
jobs:
  tests:
    env:
      POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/postgres

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2"]

    services:
      postgres:
        image: ankane/pgvector
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        run: |
          bundle exec rspec 
